use std::fmt::Write;

use anyhow::Result;

use crate::config::{RoleConfig, RoleMode};
use crate::ids::StepSlug;
use crate::io;
use crate::state::{AgentState, ProjectPaths, RolePaths};

pub const DEFAULT_PROJECT_MD: &str = r#"# Project

Describe shared project context, conventions, notation, priorities, and durable instructions that
every think-managed agent should see.
"#;

pub const DEFAULT_ROLE_MD: &str = r#"# Role

State the objective precisely. Include relevant definitions, constraints, references, and what
counts as completion.
"#;

pub const DEFAULT_STEP_MD: &str = r#"# Work

Contribute as much durable progress as possible toward the role objective. Prefer clear artifacts
that future agents can inspect, verify, extend, or reject.
"#;

const SYSTEM_PROMPT: &str = r#"# Managed think Agent

You are running inside a `think` agent. Your job is to make as much real progress as possible on
the current role.

Your durable writable workspace is `work/own/` in the agent root. It is private to this agent and
preserved across this agent's runs. `work/all/` contains read-only symlinks to other agents'
workspaces for inspection. Do not use git unless the role prompt explicitly asks you to inspect
some external repository; there is no think-managed git repo for you to operate on.

The sibling `channels/` directory contains publish outboxes, one subdirectory per project channel.
To publish an artifact, write it into the appropriate channel outbox. When your run finishes
successfully, think automatically copies outbox files into the project channel using a stable
role-agent-run-prefixed path and records the channel update. Published channel files are append-only
artifacts; do not try to edit project channel directories directly.

Use `manifest.toml` in the agent root exactly as instructed. Early in each run, write or update:

role_summary = "a short human-readable name or summary of this role"

Before exiting, write a compact final reply to the run reply file listed in the runtime summary.
It should read like the final answer you would give an operator: what you did, what changed, what
is known now, and the most important next step if one exists.

For repeatable roles, also set the `disposition` key before exiting as instructed by the current
mode. Leave notes, proof sketches, experiments, failed approaches, review material, and formal
artifacts in `work/own/`; publish only the artifacts that are meant for the shared project channel
log.
"#;

pub fn assemble(
    project: &ProjectPaths,
    role_paths: &RolePaths,
    role_config: &RoleConfig,
    agent: &AgentState,
    step: &StepSlug,
) -> Result<String> {
    let project_md = io::read_text(&project.project_md())?;
    let role_md = io::read_text(&role_paths.role_md())?;
    let step_text = io::read_text(&role_paths.step_path(step))?;
    let agent_paths = role_paths.agent(agent.agent.clone());

    let mut prompt = String::new();
    writeln!(prompt, "{SYSTEM_PROMPT}")?;
    writeln!(prompt, "\n# PROJECT.md\n\n{project_md}")?;
    writeln!(prompt, "\n# ROLE.md\n\n{role_md}")?;
    writeln!(prompt, "\n# Runtime Summary")?;
    writeln!(prompt, "\n- role: `{}`", role_paths.role)?;
    writeln!(prompt, "- agent: `{}`", agent.agent)?;
    writeln!(prompt, "- backend: `{}`", role_config.backend)?;
    writeln!(prompt, "- mode: `{}`", role_config.mode)?;
    writeln!(prompt, "- current step: `{step}`")?;
    writeln!(prompt, "- run number: `{}`", agent.run_count + 1)?;
    writeln!(
        prompt,
        "- work/own directory: `{}`",
        agent_paths.work_own().display()
    )?;
    writeln!(
        prompt,
        "- work/all directory: `{}`",
        agent_paths.work_all().display()
    )?;
    writeln!(
        prompt,
        "- run reply file: `{}`",
        agent_paths.run(agent.run_count + 1).reply().display()
    )?;
    writeln!(prompt, "- data/own: `{}`", agent_paths.data_own().display())?;
    writeln!(prompt, "- data/all: `{}`", agent_paths.data_all().display())?;
    writeln!(prompt, "\n# Publish Channels")?;
    if agent.channels.is_empty() {
        writeln!(
            prompt,
            "\nNo publish channels are configured for this project."
        )?;
    } else {
        for channel in &agent.channels {
            writeln!(
                prompt,
                "\n- `{}` outbox: `{}`",
                channel,
                agent_paths.channel_dir(channel).display()
            )?;
        }
    }
    writeln!(prompt, "\n# Mode Directive\n")?;
    writeln!(prompt, "{}", mode_directive(role_config.mode))?;
    if let Some(trigger_context) = io::read_optional_text(&agent_paths.trigger_context())?
        .filter(|text| !text.trim().is_empty())
    {
        writeln!(
            prompt,
            "\n# Trigger Context\n\nThis section was generated by think and explains why this agent was started.\n\n{}",
            trigger_context.trim()
        )?;
    }
    if let Some(exposure_context) = io::read_optional_text(&agent_paths.exposure_context())?
        .filter(|text| !text.trim().is_empty())
    {
        writeln!(
            prompt,
            "\n# Exposed Role State\n\nThis section was generated by think from this role's `expose` configuration.\n\n{}",
            exposure_context.trim()
        )?;
    }
    if let Some(agent_prompt) =
        io::read_optional_text(&agent_paths.agent_prompt())?.filter(|text| !text.trim().is_empty())
    {
        writeln!(
            prompt,
            "\n# Agent Prompt\n\nThis instruction applies only to agent `{}`.\n\n{}",
            agent.agent,
            agent_prompt.trim()
        )?;
    }
    writeln!(prompt, "\n# Agent Data\n")?;
    writeln!(
        prompt,
        "`data/own/` is your writable project-managed data directory for large raw outputs, \
         caches, logs, tables, and artifacts that should be preserved but not published."
    )?;
    writeln!(
        prompt,
        "`data/all/` contains read-only symlinks to other role agent data directories. \
         Treat everything under `data/all/` as read-only."
    )?;
    writeln!(
        prompt,
        "`work/own/` is your writable durable workspace. `work/all/` contains read-only \
         symlinks to other agents' `work/own/` directories. `channels/` contains writable \
         publish outboxes only; think publishes them after a successful run."
    )?;
    writeln!(prompt, "\n# Current Step: `{step}`\n\n{step_text}")?;
    Ok(prompt)
}

pub fn mode_directive(mode: RoleMode) -> &'static str {
    match mode {
        RoleMode::Oneshot => {
            "Ensure that absolutely all of your work is complete before terminating, because \
             another agent will not be restarted at the conclusion of your turn."
        }
        RoleMode::Repeatable => {
            "Make as much progress on your assigned work as you can. If significant work on your \
             assigned work remains and this agent should continue later, then before exiting set \
             `disposition = \"continue\"` in manifest.toml. If instead your assigned work is \
             complete as you judge it (non-pedantically, as the user intends), set \
             `disposition = \"stop\"` in manifest.toml. You must choose one of these options."
        }
        RoleMode::Infinite => {
            "Make as much progress on your role as you can. Another agent will be started to \
             continue your work after you are finished."
        }
    }
}
